replicaCount: 2

image:
  repository: 319970832249.dkr.ecr.eu-north-1.amazonaws.com/lesson-5-ecr
  tag: 5-62a5f3e
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

health:
  path: /
  
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

alerts:
  enabled: true
  cpuThresholdPercent: 70
  for: 5m
  severity: warning
  prometheusRuleLabels:
    app.kubernetes.io/name: kube-prometheus-stack
    app.kubernetes.io/instance: monitoring

config:
  POSTGRES_HOST: REPLACE_WITH_RDS_ENDPOINT
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRES_DB: mydb
  DEBUG: "False"
  ALLOWED_HOSTS: "django-app.default.svc.cluster.local,localhost,127.0.0.1"

secret:
  POSTGRES_PASSWORD: mypassword
  SECRET_KEY: "django-secret-key"