server:
  service:
    type: LoadBalancer
    port: 443

applicationsChartVersion: ${applications_chart_version}

applications:
  - name: ${app_name}
    namespace: ${app_namespace}
    project: ${argocd_project}
    source:
      repoURL: ${gitops_repo_url}
      path: ${gitops_chart_path}
      targetRevision: ${gitops_repo_branch}
      helm:
        valueFiles:
          - values.yaml
        parameters:
          - name: config.POSTGRES_HOST
            value: ${postgres_host}
          - name: config.POSTGRES_PORT
            value: ${postgres_port}
          - name: config.POSTGRES_USER
            value: ${postgres_user}
          - name: config.POSTGRES_DB
            value: ${postgres_db}
          - name: secret.POSTGRES_PASSWORD
            value: ${postgres_password}
          - name: config.DEBUG
            value: ${django_debug}
          - name: config.ALLOWED_HOSTS
            value: ${allowed_hosts}
    destination:
      server: https://kubernetes.default.svc
      namespace: ${app_namespace}
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true

repositories:
  - name: ${app_name}
    url: ${gitops_repo_url}
    username: ${repo_username}
    password: ${repo_password}

repoConfig:
  insecure: "false"
  enableLfs: "true"
